### ISSUE TITLE
Content around 'blocking' in "Adding ISR to Product page section"

### ISSUE THREAD

**Issue by mirekm** [saleor/saleor.io-learn#19]
>And then, whenever the product page than these 4 pre-generated, we will block the request till the product page is generated using fallback: 'blocking'.

Something's wrong with the first part of the sentence above. Also the second part is not fully clear to me `we will block the request till the product page is generated using fallback: 'blocking'.` especially given that it's in the section titled `Pages to generate at build-time`. Probably worth a sentence of two of explanation or rephrasing?

**Comment by zaiste** [comment]
@mirekm fixed and deployed
