### ISSUE TITLE
GraphQL Code Generator

### ISSUE THREAD

**Issue by Alfcovap51** [saleor/saleor.io-learn#21]

**Comment by zaiste** [comment]
@Alfcovap51 could you describe the issue?

**Comment by Alfcovap51** [comment]
Using the command `npm run generate` following all the instructions I get two errors: 

`  ✖ ./graphql.schema.json
    Failed to load schema from https://tutorial.saleor.cloud/graphql/:`

`✖ saleor/api.tsx
    Failed to load schema from https://tutorial.saleor.cloud/graphql/:`

I'm going through the local development tutorial but the URL for the tutorial schema seems to be not available yet.

**Comment by zaiste** [comment]
@Alfcovap51 yes, could you try this URL instead: `vercel.saleor.cloud/graphql/`? I'll fix the one from the tutorial tomorrow
