### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Mcdonoughd** [saleor/saleor.io-learn#39]
The header of https://saleor.io/  has the wrong link on mobile. Currently the "Saleor Tutorial" links to "httpshttps://saleor.io/learn" should be "https://saleor.io/learn"

While this does not apply to https://saleor.io/learn directly, I could not find a repository for the main site. If there is a better place for this issue, please close this and open a new issue there.

**Comment by karolkielecki** [comment]
@Mcdonoughd Hi there! Thanks for reporting! Indeed, there is a broken link. We'll fix it as soon as we can. Cheers and a happy new year!
